/**
 * Citizen API
 * Citizen API, for Citizen Portal frontend
 *
 * The version of the OpenAPI document: V0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShellTicket } from './shellTicket';


export interface CreateShellTicketCommand { 
    violationTicketNumber?: string;
    violationTime?: string;
    violationDate?: string;
    lastName?: string;
    givenNames?: string;
    driverLicenseNumber?: string;
    birthdate?: string;
    gender?: string;
    courtHearingLocation?: string;
    detachmentLocation?: string;
    count1Charge?: string;
    count1FineAmount?: number;
    count2Charge?: string;
    count2FineAmount?: number;
    count3Charge?: string;
    count3FineAmount?: number;
    photo?: string;
    address?: string;
    city?: string;
    province?: string;
    postalCode?: string;
    driverLicenseProvince?: string;
}

