/**
 * Citizen API
 * Citizen API, for Citizen Portal frontend
 *
 * The version of the OpenAPI document: V0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type DisputeStatus = 0 | 1 | 2 | 3 | 4;

export const DisputeStatus = {
    NUMBER_0: 0 as DisputeStatus,
    NUMBER_1: 1 as DisputeStatus,
    NUMBER_2: 2 as DisputeStatus,
    NUMBER_3: 3 as DisputeStatus,
    NUMBER_4: 4 as DisputeStatus
};

