/**
 * Citizen API
 * Citizen API, for Citizen Portal frontend
 *
 * The version of the OpenAPI document: V0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Additional } from './additional';
import { Disputant } from './disputant';
import { Offence } from './offence';


export interface TicketDispute { 
    violationTicketNumber?: string;
    violationTime?: string;
    violationDate?: string;
    disputant?: Disputant;
    additional?: Additional;
    offences?: Array<Offence>;
    discountDueDate?: string;
    discountAmount: number;
}

